### ISSUE TITLE
Apache 2.0 license on a repo with ArcGIS files

### ISSUE THREAD

**Issue by cforgaci** [cforgaci/SEIURC-assessment-framework#1]
To what extent can an Apache 2.0 license be used on a repo that contains proprietary file formats (ArcGIS `.mxd` in this case)?

**Comment by emmyft** [comment]
This is an interesting question. I'm not a licensing expert, so:
(1) let's ask the [TUD copyright helpdesk](https://www.tudelft.nl/library/copyright)?
(2) from my brief research, it looks like you can't really work with/open `.mxd` files without ESRI software... is there a possibility to export the files to a more open-friendly file format?

**Comment by cforgaci** [comment]
Thanks, @emmyft!
(1) I did write to the TUD copyright helpdesk
(2) I know that [models can be exported as graphics](https://support.esri.com/en/technical-article/000008639). Not ideal, I can try to do that, but the descriptions I give in [Appendix E](https://journals.open.tudelft.nl/plugins/generic/pdfJsViewer/pdf.js/web/viewer.html?file=https%3A%2F%2Fjournals.open.tudelft.nl%2Fabe%2Farticle%2Fdownload%2F3275%2F3447%2F8841#9789463661096-TXT.indd%3A.322609%3A59470) of the cited publication are as detailed as possible, very easy to implement in any other GIS application.

**Comment by cforgaci** [comment]
I removed the MXD files entirely as those are only the ArcGIS project files. Instead, I uploaded the toolbox with some of the models used in ArcGIS (not all analyses were recorded in models) and shared those models in Python format as well. I do not expect issues with the license in this case.
