### ISSUE TITLE
Add a project roadmap

### ISSUE THREAD

**Issue by emmyft** [cforgaci/SEIURC-assessment-framework#2]
Add a section on `README.md` on “future directions” or “roadmap” and focus on how you envision an open-source implementation of the assessment framework look like, maybe by sharing some of the info on the NLeSC proposal?

This aims to help orient people who are interested in the project to see what the next steps are, and how it relates to their work.

One way to do that is to list major milestones, e.g. complete user research, or build feature x, and put them on a timeline. Then later on you can also break them down into smaller tasks and deliverables.

**Comment by cforgaci** [comment]
I added a section [Future directions](https://github.com/cforgaci/SEIURC-assessment-framework#future-directions). Will this work?
