### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by emmyft** [cforgaci/SEIURC-assessment-framework#3]
Add a section on `README.md`, could be called "How to contribute", which details:
- Who can contribute? e.g. researchers in your field, researchers in related fields (good to specify what those related fields are), developers, etc
- How can they contribute respectively? 
- How can they stay up to date with the latest developments in this project?

**Comment by cforgaci** [comment]
I added a section [How to contribute](https://github.com/cforgaci/SEIURC-assessment-framework#how-to-contribute). Will this work?
